# Generated by Django 5.0.6 on 2024-07-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_delete_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение для превью",
                null=True,
                upload_to="blog/previews",
                verbose_name="Превью",
            ),
        ),
    ]
