# Generated by Django 5.0.6 on 2024-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_author_article_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Автор", "verbose_name_plural": "Авторы"},
        ),
        migrations.AlterField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
