# Generated by Django 5.0.6 on 2024-07-05 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Введите дату производства продукта",
                verbose_name="Дата производства",
            ),
        ),
    ]
