# Generated by Django 5.0.6 on 2024-07-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя контакта",
                        max_length=100,
                        verbose_name="Имя контакта",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите email", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Введите сообщение", verbose_name="Сообщение"
                    ),
                ),
            ],
        ),
    ]
