# Generated by Django 5.0.6 on 2024-08-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_version_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="is_current",
        ),
        migrations.AddField(
            model_name="version",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Укажите, является ли версия продукта текущей",
                verbose_name="Текущая версия",
            ),
        ),
    ]
